"""
Django settings for movies_api project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-oz+^_rgcs^a@vn%0(53%fto)h-8*h&u@pp$63#*eci4w(c0s*u'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'movies',
    'debug_toolbar',  
    'silk',  
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'silk.middleware.SilkyMiddleware',  
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'debug_toolbar.middleware.DebugToolbarMiddleware',  
]

ROOT_URLCONF = 'movies_api.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'movies_api.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Default configuration (creates new connection for each request)
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

# Optimized configuration with connection pooling
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
        'CONN_MAX_AGE': 600,  # Keep connections alive for 10 minutes (600 seconds)
        # CONN_MAX_AGE = 0 means close connection after each request (default)
        # CONN_MAX_AGE = None means persistent connections (never close)
        # CONN_MAX_AGE = 600 means reuse connection for 10 minutes
        
        # Benefits:
        # - Reduces connection overhead (no reconnect for each request)
        # - Improves performance for high-traffic applications
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Django Debug Toolbar Configuration
INTERNAL_IPS = [
    '127.0.0.1',
]

# Django Silk Configuration
SILKY_PYTHON_PROFILER = True  # Enable cProfile integration
SILKY_PYTHON_PROFILER_BINARY = True  # Use binary profiling for better performance
SILKY_PYTHON_PROFILER_RESULT_PATH = BASE_DIR / 'silk_profiles'  # Store profiles here
SILKY_MAX_REQUEST_BODY_SIZE = 1024  # Max request body size in KB
SILKY_MAX_RESPONSE_BODY_SIZE = 1024  # Max response body size in KB

# Ensure silk_profiles directory exists
import os
os.makedirs(SILKY_PYTHON_PROFILER_RESULT_PATH, exist_ok=True)

# Cache Configuration with Redis
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.redis.RedisCache',
        'LOCATION': 'redis://127.0.0.1:6379/1',
    }
}

# ============================================
# PER-SITE CACHE (Site-Wide Caching)
# ============================================
# To enable per-site caching, uncomment the lines below in MIDDLEWARE:
# 1. Add 'django.middleware.cache.UpdateCacheMiddleware' at the TOP
# 2. Add 'django.middleware.cache.FetchFromCacheMiddleware' at the BOTTOM
# 
# MIDDLEWARE = [
#     'django.middleware.cache.UpdateCacheMiddleware',  # <-- Add at TOP
#     'django.middleware.security.SecurityMiddleware',
#     ...other middleware...
#     'django.middleware.cache.FetchFromCacheMiddleware',  # <-- Add at BOTTOM
# ]
#
# Then configure these settings:
# CACHE_MIDDLEWARE_ALIAS = 'default'  # Which cache to use
# CACHE_MIDDLEWARE_SECONDS = 600  # Cache timeout (10 minutes)
# CACHE_MIDDLEWARE_KEY_PREFIX = 'mysite'  # Prefix for cache keys
