# Generated by Django 5.2.8 on 2025-11-12 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='rating',
            new_name='rating_user_idx',
            old_name='ratings_user_id_bd9bb9_idx',
        ),
        migrations.RenameIndex(
            model_name='rating',
            new_name='rating_value_idx',
            old_name='ratings_rating_105b29_idx',
        ),
        migrations.AddIndex(
            model_name='link',
            index=models.Index(fields=['imdb_id'], name='link_imdb_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['title'], name='movie_title_idx'),
        ),
    ]
